export const LOGIN_FETCH = 'LOGIN_FETCH';
export const LOGIN_DATA = 'LOGIN_DATA';
export const LOGOUT_FETCH = 'LOGOUT_FETCH';

export const GET_USERS_FETCH = 'GET_USERS_FETCH';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_DATA_BY_FILTER_FETCH = 'GET_DATA_BY_FILTER_FETCH';

export const GET_CURRENT_USER_FETCH = 'GET_CURRENT_USER_FETCH';
export const GET_CURRENT_USER_DATA = 'GET_CURRENT_USER_DATA';

export const GET_USER_DATA_FETCH = 'GET_USER_DATA_FETCH';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';

export const DELETE_USER_LABEL_FETCH = 'DELETE_USER_LABEL_FETCH';
export const ADD_USER_LABEL_FETCH = 'ADD_USER_LABEL_FETCH';
export const EDIT_USER_LABEL_FETCH = 'EDIT_USER_LABEL_FETCH';

export const CHANGE_USER_STATE_FETCH = 'CHANGE_USER_STATE_FETCH';
export const CHANGE_USER_ROLE_FETCH = 'CHANGE_USER_ROLE_FETCH';
export const CHANGE_USER_OTP_FETCH = 'CHANGE_USER_OTP_FETCH';

export const SIGN_IN_REQUIRE_2FA = 'SIGN_IN_REQUIRE_2FA';

export const ALERT_DELETE = 'ALERT_DELETE';
export const ALERT_DATA = 'ALERT_DATA';
export const ALERT_PUSH = 'ALERT_PUSH';
export const ALERT_DELETE_BY_INDEX = 'ALERT_DELETE_BY_INDEX';
